name: ansible s3

on:
  #push:
  #  branches: [main]
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir -p .environment/out
      - run: echo '<html><body><h1> Ansible S3 Integration </h1></body></html>' > .environment/out/index.html
      - uses: actions/upload-artifact@v3
        with:
          name: deploy
          path: .environment/out
  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_EC2_METADATA_DISABLED: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: setup Python virtualenv and install packages
        run: |
          # python3 -m venv py3
          # source py3/bin/activate
          # python -m pip install --upgrade pip
          # pip install boto3 botocore ansible=2.10
          echo "ANSIBLE_PYTHON_INTERPRETER=$VIRTUAL_ENV/bin/python3" >> $GITHUB_ENV
          echo "ENVIRONMENT_SETUP=true" >> $GITHUB_ENV
      - uses: actions/download-artifact@v3
        with:
          name: deploy
          path: .environment/out
      - name: files upload
        run: |
          # source py3/bin/activate
          ansible-playbook -vvvv .environment/s3.yml
